# @title
# -*- coding: utf-8 -*-
"""phase3_colab_training_improved.ipynb

Automatically generated by Colab.

# ChromatinCNN: The "MI-Fixed" Version

This notebook implements the Mechanistic Interpretability fixes to resolve "Filter Collapse":
1.  **Data-Driven Initialization**: Filters are initialized with real DNA chunks, not random noise.
2.  **Context-Aware Architecture**: Residual connections + Self-Attention to capture 200bp context.
"""

# Import libraries
import os
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim.lr_scheduler import (
    CosineAnnealingLR,
    CosineAnnealingWarmRestarts,
    LinearLR,
    SequentialLR,
    ConstantLR,
    LambdaLR,
)

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

def _detect_device() -> str:
    """Prefer CUDA, then MPS, else CPU."""
if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def _set_reproducibility(seed: int = 42, deterministic: bool = False) -> None:
    """Set seeds + (optional) deterministic flags."""
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    # Determinism can reduce throughput; keep configurable.
    if deterministic:
        try:
            torch.use_deterministic_algorithms(True)
        except Exception:
            pass
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    else:
        # Faster on CUDA.
        torch.backends.cudnn.benchmark = True


device = _detect_device()
if device == "cuda":
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
elif device == "mps":
    print("Using Apple Silicon MPS.")
else:
    print("Using CPU.")

# Mount Google Drive (optional)
try:
    from google.colab import drive
    drive.mount('/content/drive')
    CHECKPOINT_DIR = '/content/drive/MyDrive/chromatin_model_checkpoints_improved'
except ImportError:
    CHECKPOINT_DIR = './checkpoints_improved'

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
print(f"Checkpoint directory: {CHECKPOINT_DIR}")

# ==============================================================================
# CONFIGURATION
# ==============================================================================
config = {
    # Data paths (Modify as needed)
    'train_sequences': '/content/drive/MyDrive/chromatin_data/train_sequences.csv',
    'train_labels': '/content/drive/MyDrive/chromatin_data/train_labels.csv',
    'train_family_labels': '/content/drive/MyDrive/chromatin_data/train_family_labels.csv',
    'train_subcluster_labels': '/content/drive/MyDrive/chromatin_data/train_subcluster_labels.csv',
    'val_sequences': '/content/drive/MyDrive/chromatin_data/val_sequences.csv',
    'val_labels': '/content/drive/MyDrive/chromatin_data/val_labels.csv',
    'val_family_labels': '/content/drive/MyDrive/chromatin_data/val_family_labels.csv',
    'val_subcluster_labels': '/content/drive/MyDrive/chromatin_data/val_subcluster_labels.csv',
    'test_sequences': '/content/drive/MyDrive/chromatin_data/testsequences.csv',

    # Model architecture (New Attention Model)
    'n_classes': 18,
    'dropout_rate': 0.2,
    
    # We disable separate feature engineering to focus on the CNN learning correctly
    'use_engineered_features': True,
    'feature_dim': 128,
    'engineered_feature_dim_in': 5,  # gc_content, cpg_ratio, entropy, max_run_len, repeat_density
    
    # Training hyperparameters
    'learning_rate': 1e-3, # Slightly lower LR for attention model
    'warmup_epochs': 7,
    'num_epochs': 150,
    'batch_size': 1024, # Smaller batch size often helps generalization
    'num_workers': 4,
    'early_stopping_patience': 30,
    'lr_min': 1e-6,
    'warmup_start_factor': 1e-2,  # warmup LR = start_factor * learning_rate
    # Scheduler: prefer warmup + cosine WITHOUT restarts for stability.
    # (warmup_cosine_restarts can cause validation accuracy to oscillate sharply.)
    'scheduler': 'warmup_cosine',  # ['cosine', 'warmup_cosine', 'warmup_cosine_restarts']
    'scheduler_cycle_epochs': 60,   # duration (in epochs) of warmup+decay cycle irrespective of num_epochs
    'cosine_t0': 40,       # used only for warmup_cosine_restarts
    'cosine_t_mult': 2,    # used only for warmup_cosine_restarts
    
    # Regularization
    'label_smoothing': 0.02,
    'weight_decay': 1e-3, # Stronger decay for attention
    'gradient_clip_max_norm': 2.0,
    'deterministic': False,

    # Data augmentation
    'jitter_prob': 0.4,
    'jitter_min_len': 150,
    'noise_prob': 0.02,  # 0.1 is extremely strong for DNA; tends to wash out motifs
    'sequence_length': 200,
    'cache_data': True,

    # P0 Fixes
    'supcon_enabled': False, # Disable complex losses for first successful run
    # Checkpoint / resume
    # - Set to None for fresh training
    # - Or set to a path in CHECKPOINT_DIR (e.g., best_model_improved.pt / checkpoint_last.pt)
    'resume_from': None,
    'save_every_epochs': 5,  # save rolling checkpoint_last.pt every N epochs
    'use_amp': True,         # autocast+GradScaler on CUDA only

    # Hierarchy supervision (disabled when using ensemble baseline)
    'use_hierarchy': False,
    'family_embed_dim': 0,
    'family_loss_weight': 0.0,
    'subcluster_loss_weight': 0.0,

    # Hierarchical classifier (unused when use_hierarchy=False)
    'use_hierarchical_classifier': False,
    'hier_family_weight': 0.0,
    'hier_cond_weight': 0.0,
    'main_ce_weight': 1.0,

    # Ensemble settings
    'ensemble_size': 3,
}

print("Configuration:")
for key, value in config.items():
    print(f"  {key}: {value}")

_set_reproducibility(seed=42, deterministic=config.get("deterministic", False))

# ==============================================================================
# HIERARCHY UTILITIES (CSV-DERIVED)
# ==============================================================================

def _load_one_col_int_csv(path: str) -> np.ndarray:
    """Load a single-column CSV of integers into a numpy array."""
    df = pd.read_csv(path, header=None)
    values = []
    for val in df.iloc[:, 0].tolist():
        s = str(val).strip()
        try:
            values.append(int(s))
        except Exception:
            values.append(int(float(s)))
    return np.asarray(values, dtype=np.int64)


def build_hierarchy_from_data(
    label_path: str,
    family_path: str,
    subcluster_path: str,
    n_classes: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict]:
    """
    Infer label -> family/subcluster mappings directly from CSV label columns.
    Returns (label_to_family, label_to_subcluster, label_to_family_pos, meta).
    """
    labels = _load_one_col_int_csv(label_path)
    if labels.min() == 1 and labels.max() == n_classes:
        labels = labels - 1
    families = _load_one_col_int_csv(family_path)
    subclusters = _load_one_col_int_csv(subcluster_path)

    if not (len(labels) == len(families) == len(subclusters)):
        raise ValueError("Label, family, and subcluster files must have identical lengths.")

    n_families = int(families.max()) + 1
    n_subclusters = int(subclusters.max()) + 1

    label_to_family = np.zeros((n_classes,), dtype=np.int64)
    label_to_subcluster = np.zeros((n_classes,), dtype=np.int64)
    family_class_indices: list[list[int]] = [[] for _ in range(n_families)]

    for cls_idx in range(n_classes):
        mask = labels == cls_idx
        if not mask.any():
            raise ValueError(f"No samples found for class {cls_idx}.")
        fam_vals = np.unique(families[mask])
        if len(fam_vals) != 1:
            raise ValueError(f"Class {cls_idx} maps to multiple families: {fam_vals}.")
        sub_vals = np.unique(subclusters[mask])
        if len(sub_vals) != 1:
            raise ValueError(f"Class {cls_idx} maps to multiple subclusters: {sub_vals}.")
        fam_id = int(fam_vals[0])
        label_to_family[cls_idx] = fam_id
        label_to_subcluster[cls_idx] = int(sub_vals[0])
        family_class_indices[fam_id].append(cls_idx)

    label_to_family_pos = np.zeros((n_classes,), dtype=np.int64)
    for fam_id, cls_list in enumerate(family_class_indices):
        cls_list.sort()
        for pos, class_idx in enumerate(cls_list):
            label_to_family_pos[class_idx] = pos

    family_subcluster_indices: list[list[int]] = []
    subcluster_to_family = np.full((n_subclusters,), -1, dtype=np.int64)
    subcluster_to_family_pos = np.full((n_subclusters,), -1, dtype=np.int64)
    for fam_id, cls_list in enumerate(family_class_indices):
        subs = sorted({int(label_to_subcluster[idx]) for idx in cls_list})
        family_subcluster_indices.append(subs)
        for pos, sub_id in enumerate(subs):
            subcluster_to_family[sub_id] = fam_id
            subcluster_to_family_pos[sub_id] = pos

    meta = {
        "n_families": n_families,
        "n_subclusters": n_subclusters,
        "family_class_indices": family_class_indices,
        "family_subcluster_indices": family_subcluster_indices,
        "subcluster_to_family": subcluster_to_family,
        "subcluster_to_family_pos": subcluster_to_family_pos,
    }
    return label_to_family, label_to_subcluster, label_to_family_pos, meta

# ==============================================================================
# DATA LOADING UTILITIES
# ==============================================================================

def one_hot_encode(sequence: str) -> np.ndarray:
    """Convert DNA sequence to one-hot encoded array."""
    base_to_idx = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    one_hot = np.zeros((200, 4), dtype=np.float32)
    for i, base in enumerate(sequence):
        if base in base_to_idx:
            one_hot[i, base_to_idx[base]] = 1.0
        else:
            one_hot[i, :] = 0.25
    return one_hot


def compute_engineered_features(sequence: str) -> np.ndarray:
    """
    Lightweight engineered features (5 dims), aligned with Phase8 diagnostics:
    - gc_content: fraction of G/C
    - cpg_ratio: observed/expected CpG (protect against 0)
    - entropy: Shannon entropy of base frequencies
    - max_run_len: longest homopolymer run length
    - repeat_density: fraction of positions belonging to runs >= 3
    """
    s = sequence.upper()
    n = len(s) if len(s) > 0 else 1

    # Base counts
    a = s.count("A")
    c = s.count("C")
    g = s.count("G")
    t = s.count("T")
    total = a + c + g + t
    if total == 0:
        # unknown sequence: neutral defaults
        return np.array([0.5, 1.0, 2.0, 1.0, 0.0], dtype=np.float32)

    gc_content = (g + c) / total

    # CpG observed/expected
    cpg_obs = sum(1 for i in range(len(s) - 1) if s[i] == "C" and s[i + 1] == "G")
    c_freq = c / total
    g_freq = g / total
    cpg_exp = max(1e-8, (len(s) - 1) * c_freq * g_freq)
    cpg_ratio = float(cpg_obs) / float(cpg_exp)

    # Entropy (base distribution)
    p = np.array([a, c, g, t], dtype=np.float32) / float(total)
    entropy = float(-(p[p > 0] * np.log(p[p > 0])).sum())

    # Runs
    max_run = 1
    repeat_positions = 0
    run_len = 1
    for i in range(1, len(s)):
        if s[i] == s[i - 1] and s[i] in "ACGT":
            run_len += 1
        else:
            max_run = max(max_run, run_len)
            if run_len >= 3:
                repeat_positions += run_len
            run_len = 1
    max_run = max(max_run, run_len)
    if run_len >= 3:
        repeat_positions += run_len

    repeat_density = repeat_positions / max(1, len(s))

    return np.array([gc_content, cpg_ratio, entropy, float(max_run), repeat_density], dtype=np.float32)

class ChromatinDataset(Dataset):
    def __init__(self, sequences_file, labels_file=None,
                 family_labels_file=None, subcluster_labels_file=None,
                 jitter_prob=0.0, jitter_min_len=180, noise_prob=0.0, 
                 sequence_length=200, cache_data=True,
                 use_hierarchy: bool = False,
                 **kwargs):
        self.sequences_file = Path(sequences_file)
        self.labels_file = Path(labels_file) if labels_file else None
        self.jitter_prob = jitter_prob
        self.jitter_min_len = jitter_min_len
        self.noise_prob = noise_prob
        self.sequence_length = sequence_length
        self.use_hierarchy = use_hierarchy
        
        print(f"Loading sequences from {self.sequences_file}")
        sequences_df = pd.read_csv(self.sequences_file, header=None)
        self.sequences = sequences_df.iloc[:, 1].values if sequences_df.shape[1] > 1 else sequences_df[0].values
        
        self.labels = None
        if self.labels_file:
            print(f"Loading labels from {self.labels_file}")
            labels_df = pd.read_csv(self.labels_file, header=None)
            self.labels = labels_df.iloc[:, 1].values if labels_df.shape[1] > 1 else labels_df[0].values
            self.labels = self.labels - 1 # 1-18 -> 0-17

        self.family_labels = None
        self.subcluster_labels = None
        if self.use_hierarchy:
            if family_labels_file is None or subcluster_labels_file is None:
                raise ValueError("use_hierarchy=True requires family and subcluster label files.")
            fam_arr = _load_one_col_int_csv(family_labels_file)
            sub_arr = _load_one_col_int_csv(subcluster_labels_file)
            if len(fam_arr) != len(self.sequences) or len(sub_arr) != len(self.sequences):
                raise ValueError("Family/subcluster label lengths must match sequences.")
            self.family_labels = fam_arr
            self.subcluster_labels = sub_arr

        self._cached_sequences = None
        self._cached_features = None
        if cache_data:
            print("Caching one-hot encodings...")
            self._cached_sequences = [one_hot_encode(seq) for seq in self.sequences]
            if kwargs.get("use_engineered_features", True) or config.get("use_engineered_features", False):
                print("Caching engineered features...")
                self._cached_features = [compute_engineered_features(seq) for seq in self.sequences]

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        # 1. Get Sequence
        if self._cached_sequences:
            sequence = self._cached_sequences[idx].copy()
        else:
            sequence = one_hot_encode(self.sequences[idx])

        # Engineered features
        engineered = None
        if config.get("use_engineered_features", False):
            if self._cached_features is not None:
                engineered = self._cached_features[idx].copy()
            else:
                engineered = compute_engineered_features(self.sequences[idx])

        # 2. Augmentations
        if self.jitter_prob > 0 and random.random() < self.jitter_prob:
            crop_len = random.randint(self.jitter_min_len, self.sequence_length)
            start_pos = random.randint(0, self.sequence_length - crop_len)
            cropped = sequence[start_pos:start_pos+crop_len, :].copy()
            sequence = np.zeros_like(sequence)
            sequence[:cropped.shape[0], :] = cropped

        if self.noise_prob > 0:
            noise_mask = np.random.random((self.sequence_length, 4)) < self.noise_prob
            noise_seq = np.random.random((self.sequence_length, 4)).astype(np.float32)
            noise_seq /= noise_seq.sum(axis=1, keepdims=True)
            sequence[noise_mask] = noise_seq[noise_mask]

        sequence_tensor = torch.from_numpy(sequence).float()
        engineered_tensor = torch.from_numpy(engineered).float() if engineered is not None else None
        
        # Return tuple (sequence[, engineered], label[, family, subcluster])
        if self.labels is not None:
            y = int(self.labels[idx])
            if self.use_hierarchy:
                if self.family_labels is None or self.subcluster_labels is None:
                    raise ValueError("Hierarchy labels were not loaded.")
                fam = int(self.family_labels[idx])
                sub = int(self.subcluster_labels[idx])
                if engineered_tensor is not None:
                    return (
                        sequence_tensor,
                        engineered_tensor,
                        torch.tensor(y, dtype=torch.long),
                        torch.tensor(fam, dtype=torch.long),
                        torch.tensor(sub, dtype=torch.long),
                    )
                return (
                    sequence_tensor,
                    torch.tensor(y, dtype=torch.long),
                    torch.tensor(fam, dtype=torch.long),
                    torch.tensor(sub, dtype=torch.long),
                )
            if engineered_tensor is not None:
                return sequence_tensor, engineered_tensor, torch.tensor(y, dtype=torch.long)
            return sequence_tensor, torch.tensor(y, dtype=torch.long)

        if engineered_tensor is not None:
            return sequence_tensor, engineered_tensor
        return sequence_tensor

# ==============================================================================
# MODEL ARCHITECTURE (IMPROVED)
# ==============================================================================

from phase3_model.model_defs import (
    ResidualBlock,
    HierarchicalClassifier,
    ConditionalSubclusterHead,
    EnsembleModel,
    ChromatinCNNAttention
)

# ==============================================================================
# TRAINING LOOP
# ==============================================================================

def _count_parameters(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters())


def _save_checkpoint(
    path: str,
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler,
    epoch: int,
    best_val_acc: float,
    history: dict,
):
    ckpt = {
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "scheduler_state_dict": scheduler.state_dict() if scheduler is not None else None,
        "best_val_acc": best_val_acc,
        "config": config,
        "history": history,
    }
    torch.save(ckpt, path)


def _load_checkpoint(path: str, model: nn.Module, optimizer, scheduler, device: str):
    """
    Loads either:
    - a full checkpoint dict (preferred), or
    - a raw model state_dict (legacy).
    Returns: (start_epoch, best_val_acc, history)
    """
    print(f"\n[Resume] Loading checkpoint from: {path}")
    ckpt = torch.load(path, map_location=device, weights_only=False)

    # Legacy: raw state_dict
    if isinstance(ckpt, dict) and "model_state_dict" not in ckpt and all(isinstance(k, str) for k in ckpt.keys()):
        try:
            model.load_state_dict(ckpt, strict=True)
        except Exception as e:
            print(f"[Resume] Strict load failed (likely architecture changed): {e}")
            missing, unexpected = model.load_state_dict(ckpt, strict=False)
            print(f"[Resume] Loaded with strict=False. Missing keys: {len(missing)}; Unexpected keys: {len(unexpected)}")
        print("[Resume] Loaded legacy model state_dict (no optimizer/scheduler state).")
        return 1, 0.0, {'train_loss': [], 'val_acc': [], 'train_acc': [], 'val_loss': [], 'learning_rates': []}

    try:
        model.load_state_dict(ckpt["model_state_dict"], strict=True)
    except Exception as e:
        print(f"[Resume] Strict load failed (likely architecture changed): {e}")
        missing, unexpected = model.load_state_dict(ckpt["model_state_dict"], strict=False)
        print(f"[Resume] Loaded with strict=False. Missing keys: {len(missing)}; Unexpected keys: {len(unexpected)}")
    if optimizer is not None and "optimizer_state_dict" in ckpt and ckpt["optimizer_state_dict"] is not None:
        optimizer.load_state_dict(ckpt["optimizer_state_dict"])
    if scheduler is not None and "scheduler_state_dict" in ckpt and ckpt["scheduler_state_dict"] is not None:
        scheduler.load_state_dict(ckpt["scheduler_state_dict"])

    start_epoch = int(ckpt.get("epoch", 0)) + 1
    best_val_acc = float(ckpt.get("best_val_acc", 0.0))
    history = ckpt.get("history", {'train_loss': [], 'val_acc': [], 'train_acc': [], 'val_loss': [], 'learning_rates': []})
    print(f"[Resume] Resuming from epoch {start_epoch} (best_val_acc={best_val_acc:.4f})")
    return start_epoch, best_val_acc, history


def _build_scheduler(optimizer):
    scheduler_name = config.get("scheduler", "warmup_cosine")
    total_epochs = int(config["num_epochs"])
    cycle_epochs = int(config.get("scheduler_cycle_epochs", total_epochs))
    cycle_epochs = max(1, min(cycle_epochs, total_epochs))
    warmup_epochs = int(config.get("warmup_epochs", 0))
    warmup_epochs = max(0, min(warmup_epochs, cycle_epochs - 1)) if cycle_epochs > 1 else 0
    lr_min = float(config.get("lr_min", 1e-6))

    if scheduler_name == "warmup_cosine":
        schedulers: list[LinearLR | CosineAnnealingLR | ConstantLR] = []
        milestones: list[int] = []
        elapsed = 0

        if warmup_epochs > 0:
            warmup = LinearLR(
                optimizer,
                start_factor=float(config.get("warmup_start_factor", 1e-2)),
                end_factor=1.0,
                total_iters=warmup_epochs,
            )
            schedulers.append(warmup)
            elapsed += warmup_epochs
            milestones.append(elapsed)

        cosine_iters = max(1, cycle_epochs - warmup_epochs)
        cosine = CosineAnnealingLR(
            optimizer,
            T_max=cosine_iters,
            eta_min=lr_min,
        )
        schedulers.append(cosine)
        elapsed += cosine_iters
        milestones.append(elapsed)

        if elapsed < total_epochs:
            min_factor = lr_min / float(config.get("learning_rate", 1e-3))
            min_factor = max(min_factor, 0.0)
            tail = LambdaLR(optimizer, lr_lambda=lambda _: min_factor)
            schedulers.append(tail)
            milestones.append(total_epochs)

        # SequentialLR expects len(milestones) == len(schedulers) - 1
        return SequentialLR(
            optimizer,
            schedulers=schedulers,
            milestones=milestones[:-1] if len(schedulers) > 1 else [],
        )

    if scheduler_name == "warmup_cosine_restarts":
        warmup = LinearLR(
            optimizer,
            start_factor=float(config.get("warmup_start_factor", 1e-2)),
            end_factor=1.0,
            total_iters=warmup_epochs,
        )
        restarts = CosineAnnealingWarmRestarts(
            optimizer,
            T_0=int(config.get("cosine_t0", 40)),
            T_mult=int(config.get("cosine_t_mult", 2)),
            eta_min=lr_min,
        )
        return SequentialLR(optimizer, schedulers=[warmup, restarts], milestones=[warmup_epochs])

    if scheduler_name == "cosine":
        return CosineAnnealingLR(optimizer, T_max=cycle_epochs, eta_min=lr_min)

    # Fallback: no-op scheduler
    return LambdaLR(optimizer, lr_lambda=lambda _: 1.0)


def _unpack_batch(batch):
    """
    Handles the batch shapes produced by ChromatinDataset under combinations of:
    - use_engineered_features
    - use_hierarchy
    Returns: sequences, engineered_or_None, labels_or_None, fam_or_None, sub_or_None
    """
    use_feat = bool(config.get("use_engineered_features", False))
    use_h = bool(config.get("use_hierarchy", False))

    if use_feat and use_h:
        # (seq, feat, y, fam, sub)
        sequences, engineered, labels, fam, sub = batch
        return sequences, engineered, labels, fam, sub
    if use_feat and not use_h:
        # (seq, feat, y)
        sequences, engineered, labels = batch
        return sequences, engineered, labels, None, None
    if (not use_feat) and use_h:
        # (seq, y, fam, sub)
        sequences, labels, fam, sub = batch
        return sequences, None, labels, fam, sub
    # (seq, y)
    sequences, labels = batch
    return sequences, None, labels, None, None


def _aggregate_ensemble_outputs(output):
    if isinstance(output, dict):
        aggregated = {}
        for key, value in output.items():
            if value is None:
                aggregated[key] = None
            elif isinstance(value, list):
                merged_list = []
                for elem in value:
                    if elem is None:
                        merged_list.append(None)
                    else:
                        merged_list.append(elem.mean(dim=0))
                aggregated[key] = merged_list
            else:
                aggregated[key] = value.mean(dim=0)
        return aggregated
    return output.mean(dim=0)


def train():
    # 0. Hierarchy mapping (optional)
    label_to_family = None
    label_to_subcluster = None
    label_to_family_pos = None
    label_to_family_pos_tensor = None
    subcluster_to_family_pos_tensor = None
    hierarchy_meta = None
    family_class_indices = None
    family_subcluster_indices = None
    if config.get("use_hierarchy", False):
        label_to_family, label_to_subcluster, label_to_family_pos, hierarchy_meta = build_hierarchy_from_data(
            config['train_labels'],
            config['train_family_labels'],
            config['train_subcluster_labels'],
            n_classes=int(config['n_classes'])
        )
        family_class_indices = hierarchy_meta["family_class_indices"]
        family_subcluster_indices = hierarchy_meta["family_subcluster_indices"]
        label_to_family_pos_tensor = torch.from_numpy(label_to_family_pos).to(device, dtype=torch.long)
        subcluster_to_family_pos_tensor = torch.from_numpy(
            hierarchy_meta["subcluster_to_family_pos"]
        ).to(device, dtype=torch.long)
        print("\nHierarchy supervision enabled:")
        print("  source: CSV labels (train split)")
        print(f"  n_families:     {hierarchy_meta['n_families']}")
        print(f"  n_subclusters:  {hierarchy_meta['n_subclusters']}")
        print(f"  family_loss_weight:    {config.get('family_loss_weight', 0.0)}")
        print(f"  subcluster_loss_weight:{config.get('subcluster_loss_weight', 0.0)}")
        if config.get("use_hierarchical_classifier", False):
            print("  hierarchical_classifier: enabled")

    # 1. Setup Data
    train_dataset = ChromatinDataset(
        config['train_sequences'], config['train_labels'],
        family_labels_file=config.get('train_family_labels'),
        subcluster_labels_file=config.get('train_subcluster_labels'),
        jitter_prob=config['jitter_prob'],
        jitter_min_len=config['jitter_min_len'],
        noise_prob=config['noise_prob'],
        cache_data=config['cache_data'],
        use_hierarchy=bool(config.get("use_hierarchy", False)),
        use_engineered_features=bool(config.get("use_engineered_features", False)),
    )
    val_dataset = ChromatinDataset(
        config['val_sequences'], config['val_labels'],
        family_labels_file=config.get('val_family_labels'),
        subcluster_labels_file=config.get('val_subcluster_labels'),
        cache_data=config['cache_data'],
        use_hierarchy=bool(config.get("use_hierarchy", False)),
        use_engineered_features=bool(config.get("use_engineered_features", False)),
    )

    num_workers = int(config.get("num_workers", 0))
    use_pin_memory = (device in ("cuda", "mps"))
    persistent_workers = (num_workers > 0)

    train_loader = DataLoader(
        train_dataset,
        batch_size=config['batch_size'],
        shuffle=True,
        num_workers=num_workers,
        pin_memory=use_pin_memory,
        persistent_workers=persistent_workers,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=config['batch_size'],
        shuffle=False,
        num_workers=num_workers,
        pin_memory=use_pin_memory,
        persistent_workers=persistent_workers,
    )

    print("\nDataset sizes:")
    print(f"  train: {len(train_dataset):,}")
    print(f"  val:   {len(val_dataset):,}")

    # 2. Setup Model / Ensemble
    def _create_member():
        return ChromatinCNNAttention(
        n_classes=config['n_classes'],
        use_hierarchy=bool(config.get("use_hierarchy", False)),
        n_families=int(hierarchy_meta["n_families"]) if hierarchy_meta else 0,
        n_subclusters=int(hierarchy_meta["n_subclusters"]) if hierarchy_meta else 0,
        use_engineered_features=bool(config.get("use_engineered_features", False)),
        engineered_feature_dim_in=int(config.get("engineered_feature_dim_in", 5)),
        feature_dim=int(config.get("feature_dim", 128)),
        use_hierarchical_classifier=bool(config.get("use_hierarchical_classifier", False)),
            family_class_indices=family_class_indices,
            family_subcluster_indices=family_subcluster_indices,
            family_embed_dim=int(config.get("family_embed_dim", 0)),
        )

    ensemble_size = max(1, int(config.get("ensemble_size", 1)))
    if ensemble_size > 1:
        members = [_create_member() for _ in range(ensemble_size)]
        model = EnsembleModel(members)
        print(f"\nEnsemble enabled: {ensemble_size} members")
    else:
        model = _create_member()
    model = model.to(device)
    print(f"\nModel: {model.__class__.__name__}")
    print(f"Total parameters: {_count_parameters(model):,}")
    
    # 3. APPLY MI FIX: Data-Driven Initialization
    model.init_filters_from_data(train_loader)
    
    # 4. Optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=config['learning_rate'], weight_decay=config['weight_decay'])
    scheduler = _build_scheduler(optimizer)
    criterion = nn.CrossEntropyLoss(label_smoothing=config['label_smoothing'])
    family_criterion = nn.CrossEntropyLoss()
    subcluster_criterion = nn.CrossEntropyLoss()
    
    # 5. Loop
    start_epoch = 1
    best_val_acc = 0.0
    history = {
        'train_loss': [],
        'train_acc': [],
        'val_loss': [],
        'val_acc': [],
        'learning_rates': [],
        'train_ce_loss': [],
        'train_family_loss': [],
        'train_subcluster_loss': [],
        'train_hier_family_loss': [],
        'train_hier_cond_loss': [],
        'val_ce_loss': [],
        'val_family_loss': [],
        'val_subcluster_loss': [],
        'val_hier_family_loss': [],
        'val_hier_cond_loss': [],
    }

    # Resume (optional)
    if config.get("resume_from"):
        start_epoch, best_val_acc, history = _load_checkpoint(
            config["resume_from"], model, optimizer, scheduler, device
        )

    # AMP (CUDA only)
    use_amp = bool(config.get("use_amp", True)) and (device == "cuda")
    scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
    
    print("\nStarting training...")
    print(f"  start_epoch: {start_epoch}")
    print(f"  num_epochs:  {config['num_epochs']}")
    print(f"  scheduler:   {config.get('scheduler')}")
    print(f"  AMP:         {use_amp}")

    patience_counter = 0

    for epoch in range(start_epoch, config['num_epochs'] + 1):
        model.train()
        train_loss = 0.0
        train_ce_loss_total = 0.0
        train_fam_loss_total = 0.0
        train_sub_loss_total = 0.0
        train_hier_family_loss_total = 0.0
        train_hier_cond_loss_total = 0.0
        train_correct = 0
        train_total = 0
        fam_correct = 0
        fam_total = 0
        sub_correct = 0
        sub_total = 0
        
        pbar = tqdm(train_loader, desc=f"Epoch {epoch}")
        for batch in pbar:
            sequences, engineered, labels, fam_labels, sub_labels = _unpack_batch(batch)
            sequences = sequences.to(device)
            labels = labels.to(device)
            engineered = engineered.to(device) if engineered is not None else None
            fam_labels = fam_labels.to(device) if fam_labels is not None else None
            sub_labels = sub_labels.to(device) if sub_labels is not None else None
            
            # Forward
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=use_amp):
                out_fwd = model(sequences, engineered=engineered)
                if ensemble_size > 1:
                    out_fwd = _aggregate_ensemble_outputs(out_fwd)
                family_cond_logits = None
                sub_cond_logits = None
                if config.get("use_hierarchy", False):
                    logits = out_fwd["logits_class"]
                    logits_fam = out_fwd["logits_family"]
                    logits_sub = out_fwd["logits_subcluster"]
                    family_cond_logits = out_fwd.get("family_cond_logits")
                    sub_cond_logits = out_fwd.get("sub_cond_logits")
                else:
                    logits = out_fwd
                    logits_fam = None
                    logits_sub = None

                ce_loss = criterion(logits, labels)
                loss = float(config.get("main_ce_weight", 1.0)) * ce_loss

                hier_family_loss = torch.tensor(0.0, device=device)
                hier_cond_loss = torch.tensor(0.0, device=device)
                fam_loss = torch.tensor(0.0, device=device)
                sub_loss = torch.tensor(0.0, device=device)

                if (
                    config.get("use_hierarchical_classifier", False)
                    and family_cond_logits is not None
                    and label_to_family_pos_tensor is not None
                ):
                    fam_pos = label_to_family_pos_tensor[labels]
                    hier_family_loss = family_criterion(logits_fam, fam_labels)
                    cond_loss_sum = torch.tensor(0.0, device=device)
                    cond_count = 0
                    for fam_id, cls_list in enumerate(family_class_indices or []):
                        head_logits = family_cond_logits[fam_id] if family_cond_logits else None
                        if head_logits is None or len(cls_list) == 0:
                            continue
                        mask = (fam_labels == fam_id)
                        if mask.any():
                            cond_loss_sum = cond_loss_sum + criterion(head_logits[mask], fam_pos[mask])
                        cond_count += 1
                    if cond_count > 0:
                        hier_cond_loss = cond_loss_sum / cond_count
                    loss = loss + float(config.get("hier_family_weight", 0.0)) * hier_family_loss
                    loss = loss + float(config.get("hier_cond_weight", 0.0)) * hier_cond_loss
                elif logits_fam is not None and fam_labels is not None:
                    fam_loss = family_criterion(logits_fam, fam_labels)
                    loss = loss + float(config.get("family_loss_weight", 0.0)) * fam_loss

                if config.get("use_hierarchy", False):
                    if sub_cond_logits is not None and subcluster_to_family_pos_tensor is not None:
                        sub_pos = subcluster_to_family_pos_tensor[sub_labels]
                        sub_loss_sum = torch.tensor(0.0, device=device)
                        sub_count = 0
                        for fam_id, sub_ids in enumerate(family_subcluster_indices or []):
                            head_logits = sub_cond_logits[fam_id] if sub_cond_logits else None
                            if head_logits is None or len(sub_ids) == 0:
                                continue
                            mask = (fam_labels == fam_id)
                            if mask.any():
                                sub_loss_sum = sub_loss_sum + subcluster_criterion(head_logits[mask], sub_pos[mask])
                                sub_count += 1
                        if sub_count > 0:
                            sub_loss = sub_loss_sum / sub_count
                            loss = loss + float(config.get("subcluster_loss_weight", 0.0)) * sub_loss
                    elif logits_sub is not None and sub_labels is not None:
                        sub_loss = subcluster_criterion(logits_sub, sub_labels)
                        loss = loss + float(config.get("subcluster_loss_weight", 0.0)) * sub_loss

            optimizer.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), config['gradient_clip_max_norm'])
            scaler.step(optimizer)
            scaler.update()
            
            train_loss += loss.item()
            train_ce_loss_total += float(ce_loss.detach().item())
            if config.get("use_hierarchy", False):
                if fam_loss is not None:
                    train_fam_loss_total += float(fam_loss.detach().item())
                if sub_loss is not None:
                    train_sub_loss_total += float(sub_loss.detach().item())
            if config.get("use_hierarchical_classifier", False):
                train_hier_family_loss_total += float(hier_family_loss.detach().item())
                train_hier_cond_loss_total += float(hier_cond_loss.detach().item())
            _, pred = torch.max(logits, dim=1)
            train_correct += (pred == labels).sum().item()
            train_total += labels.size(0)

            if config.get("use_hierarchy", False):
                if logits_fam is not None:
                    _, fam_pred = torch.max(logits_fam, dim=1)
                    fam_correct += (fam_pred == fam_labels).sum().item()
                    fam_total += fam_labels.size(0)
                if logits_sub is not None:
                    _, sub_pred = torch.max(logits_sub, dim=1)
                    sub_correct += (sub_pred == sub_labels).sum().item()
                    sub_total += sub_labels.size(0)

            pbar.set_postfix({
                'loss': f"{loss.item():.4f}",
                'lr': f"{optimizer.param_groups[0]['lr']:.2e}",
            })
        
        # Validation
        model.eval()
        val_loss_total = 0.0
        val_ce_loss_total = 0.0
        val_fam_loss_total = 0.0
        val_sub_loss_total = 0.0
        val_hier_family_loss_total = 0.0
        val_hier_cond_loss_total = 0.0
        val_correct = 0
        val_total = 0
        val_fam_correct = 0
        val_fam_total = 0
        val_sub_correct = 0
        val_sub_total = 0
        with torch.no_grad():
            for batch in val_loader:
                sequences, engineered, labels, fam_labels, sub_labels = _unpack_batch(batch)
                sequences = sequences.to(device)
                labels = labels.to(device)
                engineered = engineered.to(device) if engineered is not None else None
                fam_labels = fam_labels.to(device) if fam_labels is not None else None
                sub_labels = sub_labels.to(device) if sub_labels is not None else None

                out = model(sequences, engineered=engineered)
                if ensemble_size > 1:
                    out = _aggregate_ensemble_outputs(out)
                family_cond_logits = None
                sub_cond_logits = None
                if config.get("use_hierarchy", False):
                    logits = out["logits_class"]
                    logits_fam = out["logits_family"]
                    logits_sub = out["logits_subcluster"]
                    family_cond_logits = out.get("family_cond_logits")
                    sub_cond_logits = out.get("sub_cond_logits")
                else:
                    logits = out
                    logits_fam = None
                    logits_sub = None

                ce_loss = criterion(logits, labels)
                val_loss = float(config.get("main_ce_weight", 1.0)) * ce_loss

                hier_family_loss = torch.tensor(0.0, device=device)
                hier_cond_loss = torch.tensor(0.0, device=device)
                fam_loss = torch.tensor(0.0, device=device)
                sub_loss = torch.tensor(0.0, device=device)

                if (
                    config.get("use_hierarchical_classifier", False)
                    and family_cond_logits is not None
                    and label_to_family_pos_tensor is not None
                ):
                    fam_pos = label_to_family_pos_tensor[labels]
                    hier_family_loss = family_criterion(logits_fam, fam_labels)
                    cond_loss_sum = torch.tensor(0.0, device=device)
                    cond_count = 0
                    for fam_id, cls_list in enumerate(family_class_indices or []):
                        head_logits = family_cond_logits[fam_id] if family_cond_logits else None
                        if head_logits is None or len(cls_list) == 0:
                            continue
                        mask = (fam_labels == fam_id)
                        if mask.any():
                            cond_loss_sum = cond_loss_sum + criterion(head_logits[mask], fam_pos[mask])
                            cond_count += 1
                    if cond_count > 0:
                        hier_cond_loss = cond_loss_sum / cond_count
                    val_loss = val_loss + float(config.get("hier_family_weight", 0.0)) * hier_family_loss
                    val_loss = val_loss + float(config.get("hier_cond_weight", 0.0)) * hier_cond_loss
                elif logits_fam is not None and fam_labels is not None:
                    fam_loss = family_criterion(logits_fam, fam_labels)
                    val_loss = val_loss + float(config.get("family_loss_weight", 0.0)) * fam_loss

                if config.get("use_hierarchy", False):
                    if sub_cond_logits is not None and subcluster_to_family_pos_tensor is not None:
                        sub_pos = subcluster_to_family_pos_tensor[sub_labels]
                        sub_loss_sum = torch.tensor(0.0, device=device)
                        sub_count = 0
                        for fam_id, sub_ids in enumerate(family_subcluster_indices or []):
                            head_logits = sub_cond_logits[fam_id] if sub_cond_logits else None
                            if head_logits is None or len(sub_ids) == 0:
                                continue
                            mask = (fam_labels == fam_id)
                            if mask.any():
                                sub_loss_sum = sub_loss_sum + subcluster_criterion(head_logits[mask], sub_pos[mask])
                                sub_count += 1
                        if sub_count > 0:
                            sub_loss = sub_loss_sum / sub_count
                            val_loss = val_loss + float(config.get("subcluster_loss_weight", 0.0)) * sub_loss
                    elif logits_sub is not None and sub_labels is not None:
                        sub_loss = subcluster_criterion(logits_sub, sub_labels)
                        val_loss = val_loss + float(config.get("subcluster_loss_weight", 0.0)) * sub_loss

                val_loss_total += float(val_loss.item())
                val_ce_loss_total += float(ce_loss.detach().item())
                if config.get("use_hierarchy", False):
                    if fam_loss is not None:
                        val_fam_loss_total += float(fam_loss.detach().item())
                    if sub_loss is not None:
                        val_sub_loss_total += float(sub_loss.detach().item())
                if config.get("use_hierarchical_classifier", False):
                    val_hier_family_loss_total += float(hier_family_loss.detach().item())
                    val_hier_cond_loss_total += float(hier_cond_loss.detach().item())

                if config.get("use_hierarchy", False):
                    if logits_fam is not None:
                        _, fam_pred = torch.max(logits_fam, dim=1)
                        val_fam_correct += (fam_pred == fam_labels).sum().item()
                        val_fam_total += fam_labels.size(0)
                    if logits_sub is not None:
                        _, sub_pred = torch.max(logits_sub, dim=1)
                        val_sub_correct += (sub_pred == sub_labels).sum().item()
                        val_sub_total += sub_labels.size(0)

                _, pred = torch.max(logits, dim=1)
                val_correct += (pred == labels).sum().item()
                val_total += labels.size(0)

        val_acc = (val_correct / val_total) if val_total > 0 else 0.0
        train_acc = (train_correct / train_total) if train_total > 0 else 0.0
        train_fam_acc = (fam_correct / fam_total) if fam_total > 0 else 0.0
        train_sub_acc = (sub_correct / sub_total) if sub_total > 0 else 0.0
        val_fam_acc = (val_fam_correct / val_fam_total) if val_fam_total > 0 else 0.0
        val_sub_acc = (val_sub_correct / val_sub_total) if val_sub_total > 0 else 0.0
        train_loss_avg = train_loss / len(train_loader)
        train_ce_loss_avg = train_ce_loss_total / len(train_loader)
        train_fam_loss_avg = train_fam_loss_total / len(train_loader)
        train_sub_loss_avg = train_sub_loss_total / len(train_loader)
        train_hier_family_loss_avg = train_hier_family_loss_total / len(train_loader)
        train_hier_cond_loss_avg = train_hier_cond_loss_total / len(train_loader)
        val_loss_avg = val_loss_total / len(val_loader)
        val_ce_loss_avg = val_ce_loss_total / len(val_loader)
        val_fam_loss_avg = val_fam_loss_total / len(val_loader)
        val_sub_loss_avg = val_sub_loss_total / len(val_loader)
        val_hier_family_loss_avg = val_hier_family_loss_total / len(val_loader)
        val_hier_cond_loss_avg = val_hier_cond_loss_total / len(val_loader)

        # Step scheduler AFTER validation to keep reporting aligned with epoch summary.
        scheduler.step()
        current_lr = optimizer.param_groups[0]['lr']

        history['train_loss'].append(train_loss_avg)
        history['train_acc'].append(train_acc)
        history['val_loss'].append(val_loss_avg)
        history['val_acc'].append(val_acc)
        history['learning_rates'].append(current_lr)
        history['train_ce_loss'].append(train_ce_loss_avg)
        history['train_family_loss'].append(train_fam_loss_avg)
        history['train_subcluster_loss'].append(train_sub_loss_avg)
        history['train_hier_family_loss'].append(train_hier_family_loss_avg)
        history['train_hier_cond_loss'].append(train_hier_cond_loss_avg)
        history['val_ce_loss'].append(val_ce_loss_avg)
        history['val_family_loss'].append(val_fam_loss_avg)
        history['val_subcluster_loss'].append(val_sub_loss_avg)
        history['val_hier_family_loss'].append(val_hier_family_loss_avg)
        history['val_hier_cond_loss'].append(val_hier_cond_loss_avg)

        print(
            f"Epoch {epoch:03d} | "
            f"LR: {current_lr:.2e} | "
            f"Train Loss: {train_loss_avg:.4f} [CE {train_ce_loss_avg:.4f}, hier_f {train_hier_family_loss_avg:.3f}, hier_c {train_hier_cond_loss_avg:.3f}, fam {train_fam_loss_avg:.3f}, sub {train_sub_loss_avg:.3f}] | "
            f"Val Loss: {val_loss_avg:.4f} [CE {val_ce_loss_avg:.4f}, hier_f {val_hier_family_loss_avg:.3f}, hier_c {val_hier_cond_loss_avg:.3f}, fam {val_fam_loss_avg:.3f}, sub {val_sub_loss_avg:.3f}] | "
            f"Val Acc: {val_acc:.4f}"
        )
        if config.get("use_hierarchy", False):
            print(
                f"           Aux | "
                f"Train fam: {train_fam_acc:.3f} sub: {train_sub_acc:.3f} | "
                f"Val fam: {val_fam_acc:.3f} sub: {val_sub_acc:.3f}"
            )
        
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_path = os.path.join(CHECKPOINT_DIR, 'best_model_improved.pt')
            _save_checkpoint(best_path, model, optimizer, scheduler, epoch, best_val_acc, history)
            print(f"--> New Best Checkpoint Saved (Acc: {best_val_acc:.4f})")
            patience_counter = 0
        else:
            patience_counter += 1

        # Rolling checkpoint (for resume safety)
        save_every = int(config.get("save_every_epochs", 0) or 0)
        if save_every > 0 and (epoch % save_every == 0):
            last_path = os.path.join(CHECKPOINT_DIR, 'checkpoint_last.pt')
            _save_checkpoint(last_path, model, optimizer, scheduler, epoch, best_val_acc, history)
            print(f"--> Saved rolling checkpoint: checkpoint_last.pt (epoch {epoch})")

        # Early stopping
        if patience_counter >= int(config.get("early_stopping_patience", 30)):
            print(f"Early stopping: no improvement for {patience_counter} epoch(s).")
            break
            
    print("Training Complete.")
    
    # Save History
    with open(os.path.join(CHECKPOINT_DIR, 'history.json'), 'w') as f:
        json.dump(history, f)


if __name__ == "__main__":
    train()
